{{- if .Values.authConfigSync.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-dc-auth-config
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "kube-dc.chart" . }}
    app.kubernetes.io/name: kube-dc
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: auth-config
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    helm.sh/resource-policy: keep
data:
  {{ .Values.manager.kubernetesAuthConfig.filename }}: |
    jwt: []
{{- end }}
