{{- if .Values.backend.gateway.enabled }}
{{- $fullName := include "kube-dc.backend.fullname" . -}}
{{- $svcPort := .Values.backend.service.port -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "kube-dc.backend.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.backend.gateway.parentRef.name | default "eg" }}
    namespace: {{ .Values.backend.gateway.parentRef.namespace | default "envoy-gateway-system" }}
    sectionName: {{ .Values.backend.gateway.parentRef.sectionName | default "https-backend" }}
  hostnames:
  - {{ .Values.backend.ingress.host }}
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: {{ $fullName }}
      port: {{ $svcPort }}
{{- end }}
