{{- if .Values.k8Manager.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kube-dc.k8manager.fullname" . }}
  labels:
    {{- include "kube-dc.k8manager.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "kube-dc.k8manager.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "kube-dc.k8manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
