{{- if .Values.k8Manager.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-dc.k8manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-dc.k8manager.labels" . | nindent 4 }}
{{- end }}
